### ISSUE TITLE
Safari Crypto.getRandomValues error

### ISSUE THREAD

**Issue by threeseed** [scala-js/scala-js-java-securerandom#9]
Getting the following error on Safari Mac (17614.1.25.9.10, 17614):

```
Can only call Crypto.getRandomValues on instances of Crypto
```

Does not appear in Chrome.  

Looks like it was an [issue](https://ask.clojure.org/index.php/6266/random-uuid-should-cryptographically-strong-prng-available?start=15) with the ClosureScript implementation as well.

**Comment by armanbilge** [comment]
I think this is similar to an error we encountered in https://github.com/scala-js/scala-js-dom/pull/669 as well.

Chrome: `TypeError: Illegal invocation`
Firefox: `TypeError: 'getRandomValues' called on an object that does not implement interface Crypto.`

We should add Safari to CI.

**Comment by armanbilge** [comment]
Actually @nadenf: can you confirm that your code does not throw an error in Chrome and/or Firefox? It's not obvious to me why Safari would behave differently here.

**Comment by threeseed** [comment]
@armanbilge .. Had the same "Illegal invocation" error in Chrome as well but thought it was unrelated.

Ends up working if I switch to: scalajs-fake-insecure-java-securerandom.

**Comment by sjrd** [comment]
> Ends up working if I switch to: scalajs-fake-insecure-java-securerandom.

Please don't. This doesn't do what you want. It's *insecure*.

**Comment by sjrd** [comment]
It seems some browsers don't like what amounts to the following:
```js
const getRV = crypto.getRandomValues;
getRV(...);
```
They want a direct invocation like
```js
crypto.getRandomValues(...);
```

**Comment by sjrd** [comment]
Hum no but that doesn't make sense. We *already* call `crypto.getRandomValues(buffer)` exactly like that. Even Firefox complains if we do `getRV(buffer)`.

So what is different on Safari? Also, how did you observe a failure in Chrome, even though we have Chrome set up in the CI?

There must be something else missing here. Are you using some kind of bundler that attempts to provide a polyfill of `getRandomValues`, perhaps? Or of the Node.js `crypto` module? Then perhaps it messes up and causes these issues?

**Comment by sjrd** [comment]
I just did a test of `testSuiteJS/testHtml` on Safari, and the test suite passes in the browser. Therefore, I don't think this is an issue with this project at all. As I mentioned above, I suspect it's something to do with a bundling setup on your side.
